### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by Siprah** [michaeldegroot/symfony-gulp#1]
I'm using OS X 10.11. After install package, I'm getting error `env: node\r: No such file or directory`. I know `\r` is an carriage return special character. But I think it shouldn't be added.

**Comment by michaeldegroot** [comment]
Seems like a windows newline issue in OSX. Will fix this asap

**Comment by michaeldegroot** [comment]
Closing this for now unless you are having any more problems

**Comment by Siprah** [comment]
Thanks 😄
